export * from './controller/student.controller';
export * from './service/student.service';
export * from './repository/student.repository.interface';
export * from './repository/student.repository.firebase';
export * from './dto/create-student.dto';
export * from './dto/update-student.dto';
export * from './validators/student.validator';
export * from './types/student.type';
export * from './routes/student.routes';